vc_creds: {user: "msabadac@vsphere.local", pass: "{{ vc_user01 }}"}
vc_host: 198.19.202.251
vc_datacenter: NYC
vc_prodvm: CLUS_User01_ProdVM
vc_prodvm_mac: 00:50:56:ad:32:35
vc_prodvm_ip: 30.0.1.10
vc_prodvm_int: ens161
vc_prodvm_creds: {user: "clusadmin", pass: "{{ vc_user01_prodvm }}"}
vc_testvm: CLUS_User01_TestVM
vc_testvm_mac: 00:50:56:ad:dd:85
vc_testvm_ip: 30.0.1.11
vc_testvm_int: ens160
vc_testvm_creds: {user: "clus-test", pass: "{{ vc_user01_testvm }}"}
vc_pg: CLUS-user01|CLUS_user01_AP|EPG_Frontend