version: '3'
services:
  backend:
    image: sabaroof/ciscolive2022:backend
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    extra_hosts:
      - "web:150.0.1.5"
      - "mongo:150.0.3.5"

