version: '3'
services:
  backend:
    image: sabaroof/ciscolive2022:backend
    ports: 
      - "9091:9091"
      - "9090:9090"
    volumes:
      - ./flask:/src
    extra_hosts:
      - "web:150.0.1.5"
      - "mongo:150.0.3.5"

