version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=20.0.2.2:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend
    networks: 
      - frontend
  backend:
    image: sabaroof/ciscolive2022:backend
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      - mongo
    networks: 
      - backend
  mongo:
    image: mongo
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks: 
      - db

networks:
  frontend:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.1.0/24
          gateway: 20.0.1.1
    driver_opts:
      ipvlan_mode: l2
    name: frontend_net
  backend:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.2.0/24    
          gateway: 20.0.2.1
    driver_opts:      
      ipvlan_mode: l2
    name: backend_net
  db:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.3.0/24
          gateway: 20.0.3.1
    driver_opts:
      ipvlan_mode: l2
    name: db_net

