version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    extra_hosts:
      - "backend:20.0.2.2"
      - "mongo:20.0.3.2"
    depends_on:
      - backend
    networks: 
      frontend:
        ipv4_address: 20.0.1.2
  backend:
    image: sabaroof/ciscolive2022:backend
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      - mongo
    extra_hosts:
      - "web:20.0.1.2"
      - "mongo:20.0.3.2"
    networks: 
      backend:
        ipv4_address: 20.0.2.2
  mongo:
    image: mongo
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    extra_hosts:
      - "backend:20.0.2.2"
      - "web:20.0.1.2"
    networks: 
      db:
        ipv4_address: 20.0.3.2

networks:
  frontend:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.1.0/24
          gateway: 20.0.1.1
    driver_opts:
      ipvlan_mode: l2
      parent: ens192
    name: frontend_net
  backend:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.2.0/24    
          gateway: 20.0.2.1
    driver_opts:      
      ipvlan_mode: l2
      parent: ens224
    name: backend_net
  db:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 20.0.3.0/24
          gateway: 20.0.3.1
    driver_opts:
      ipvlan_mode: l2
      parent: ens256
    name: db_net

