- name: Test playbook for Task1
  hosts: apic1 vcenter1
  gather_facts: no
  vars_files: inventory.yml
  connection: httpapi

  tasks:

    - name: Create BDs for the frontend, backend and database tiers
      cisco.aci.aci_bd:
        host: '{{ ansible_host }}'
        username: '{{ ansible_user }}'
        password: '{{ ansible_pass }}'
        tenant: '{{ ansible_tenant }}'
        vrf: 'clus_user01_vrf_1'
        bd: 'BD_{{item}}'
        validate_certs: no
        state: present  
      loop: '{{ ["frontend_test", "backend_test", "db_test"] }}'