- name: Test playbook for Task1 with NDO
  hosts: ndo
  gather_facts: no
  vars_files: inventory.yml
  connection: httpapi

  tasks:

  - name: Stretch the cloud tenant to an on prem site
    cisco.mso.mso_tenant_site:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tenant: Working_TENANT
      site: New York
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Associate the on prem site with the template
    cisco.mso.mso_schema_site:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      site: New York
      template: Final_TEMPLATE
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Configure the template to deploy the BDs
    cisco.mso.mso_schema_template_bd:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      bd: 'BD_{{ item }}'
      vrf:
        name: CLUS_VRF
      state: present
      validate_certs: no
    delegate_to: localhost
    loop: '{{ ["Frontend", "Backend", "DB"] }}'

  - name: Configure the template to deploy the frontend subnet
    cisco.mso.mso_schema_template_bd_subnet:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      bd: BD_Frontend
      subnet: 50.0.1.1/24
      state: present
      scope: public
      validate_certs: no
    delegate_to: localhost    
  
  - name: Configure the template to deploy the backend subnet
    cisco.mso.mso_schema_template_bd_subnet:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      bd: BD_Backend
      subnet: 50.0.2.1/24
      state: present
      scope: public
      validate_certs: no
    delegate_to: localhost 

  - name: Configure the template to deploy the db subnet
    cisco.mso.mso_schema_template_bd_subnet:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      bd: BD_DB
      subnet: 50.0.3.1/24
      state: present
      scope: public
      validate_certs: no
    delegate_to: localhost 

  - name: Create frontend EPG
    cisco.mso.mso_schema_template_anp_epg:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Frontend
      bd:
        name: BD_Frontend
      vrf:
        name: CLUS_VRF
      state: present
      validate_certs: no
    delegate_to: localhost       

  - name: Create backend EPG
    cisco.mso.mso_schema_template_anp_epg:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Backend
      bd:
        name: BD_Backend
      vrf:
        name: CLUS_VRF
      state: present
      validate_certs: no
    delegate_to: localhost   

  - name: Create db EPG
    cisco.mso.mso_schema_template_anp_epg:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_DB
      bd:
        name: BD_DB
      vrf:
        name: CLUS_VRF
      state: present
      validate_certs: no
    delegate_to: localhost   

  - name: Attach the VMM domain to the created EPGs
    cisco.mso.mso_schema_site_anp_epg_domain:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      site: New York
      anp: CLUS_ANP
      epg: 'EPG_{{item}}'
      domain_association_type: vmmDomain
      domain_profile: nyc-dvs
      deployment_immediacy: immediate
      resolution_immediacy: immediate
      enhanced_lagpolicy_name: nyc-lag
      enhanced_lagpolicy_dn: uni/vmmp-VMware/dom-nyc-dvs/vswitchpolcont/enlacplagp-nyc-lag 
      state: present
      validate_certs: no
    delegate_to: localhost  
    loop: '{{ ["Frontend", "Backend", "DB"] }}'

  - name: Add a selector to cloud site frontend EPG
    cisco.mso.mso_schema_site_anp_epg_selector:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      site: AWSSite
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Frontend
      selector: selector_frontend
      expressions:
        - type: ip_address
          operator: equals
          value: 150.0.1.0/24
      state: present
      validate_certs: no
    delegate_to: localhost
    
  - name: Add a selector to cloud site backend EPG
    cisco.mso.mso_schema_site_anp_epg_selector:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      site: AWSSite
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Backend
      selector: selector_backend
      expressions:
        - type: ip_address
          operator: equals
          value: 150.0.2.0/24
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Add a selector to cloud site DB EPG
    cisco.mso.mso_schema_site_anp_epg_selector:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      site: AWSSite
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_DB
      selector: selector_db
      expressions:
        - type: ip_address
          operator: equals
          value: 150.0.3.0/24
      state: present
      validate_certs: no
    delegate_to: localhost 

  - name: Add a new contract filter
    cisco.mso.mso_schema_template_contract_filter:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      contract: CLUS_Contract
      contract_scope: vrf
      filter: CLUS_AnyFilter
      action: permit
      state: present
      validate_certs: no
    delegate_to: localhost   

  - name: Add a new filter entry
    cisco.mso.mso_schema_template_filter_entry:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      filter: CLUS_AnyFilter
      entry: CLUS_AnyFilterEntry
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Add a contract to a frontend EPG
    cisco.mso.mso_schema_template_anp_epg_contract:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Frontend
      contract:
        name: CLUS_Contract
        type: consumer
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Add a contract to a backend EPG
    cisco.mso.mso_schema_template_anp_epg_contract:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Backend
      contract:
        name: CLUS_Contract
        type: provider
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Add a contract to a backend EPG
    cisco.mso.mso_schema_template_anp_epg_contract:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_Backend
      contract:
        name: CLUS_Contract
        type: consumer
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Add a contract to a db EPG
    cisco.mso.mso_schema_template_anp_epg_contract:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      anp: CLUS_ANP
      epg: EPG_DB
      contract:
        name: CLUS_Contract
        type: provider
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Deploy a schema template
    cisco.mso.mso_schema_template_deploy:
      host: '{{ mso_host }}'
      username: '{{ username }}'
      password: '{{ password }}'
      schema: Final_SCHEMA
      template: Final_TEMPLATE
      state: deploy
      validate_certs: no
    delegate_to: localhost